name: Release new version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false   # use GITHUB_TOKEN
        fetch-depth: 1               # fetch depth is nr of commits

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyriksdagen

    #- name: dump stuff
    #  run: |
    #    mkdir dumps
    #    python -c 'from pyriksdagen.reference_handling import compile_bib_list; compile_bib_list(output_file="dumps/reference-list.bib")'

    #- name: zip dumps
    #  run: zip dumps.zip dumps

    - name: Zip corpus
      run: |
        zip -r volumeG.zip data

    #- name: zip quality estimates
    #  run: zip -r quality.zip quality/estimates

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.zip
        tag: ${{ github.ref }}
        file_glob: true
